name: Deploy em Produção

on:
  push:
    tags:
      - 'v*.*.*' # Dispara apenas em tags como v1.0.0, v2.1.3

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Gera metadados para taguear corretamente (v1.0.0 e latest)
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./app 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy no Servidor EC2 de Produção
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_PROD }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Login
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Puxar a versão específica da tag atual
            docker pull ghcr.io/matheuslimams/desafio-lacrei-app:${{ github.ref_name }}
            
            # Limpeza
            docker stop lacrei-container || true
            docker rm lacrei-container || true
            
            # Execução Container
            docker run -d \
              -p 3000:3000 \
              --restart unless-stopped \
              --log-driver=awslogs \
              --log-opt awslogs-region=us-east-1 \
              --log-opt awslogs-group=lacrei-prod-logs \
              --log-opt awslogs-create-group=true \
              -e NODE_ENV=production \
              -e DOMAIN_NAME=lacrei-production.sparkflux.com.br \
              --name lacrei-container \
              ghcr.io/matheuslimams/desafio-lacrei-app:${{ github.ref_name }}

      - name: Validar Deploy de Produção (Smoke Test)
        run: |
          sleep 10
          curl -f --retry 3 --retry-delay 3 https://lacrei-production.sparkflux.com.br/status