name: Deploy em Staging

on:
  push:
    branches: [main]

jobs:
   build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: ghcr.io/matheuzlima/desafio-lacrei-app:latest

      - name: Deploy no Servidor EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            set -e
            echo "üîé Verificando ambiente para deploy da aplica√ß√£o..."
            # Verifica se Docker j√° existe
            if ! command -v docker &> /dev/null
            then
              echo "‚ùå Docker n√£o encontrado. Instalando..."
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
            else
              echo "‚úÖ Docker j√° est√° instalado. Pulando etapa..."
            fi
            docker pull ghcr.io/matheuzlima/desafio-lacrei-app:latest
            docker stop lacrei-container || true
            docker rm lacrei-container || true
            docker run -d \
              -p 3000:3000 \
              --log-driver=awslogs \
              --log-opt awslogs-region=us-east-1 \
              --log-opt awslogs-group=lacrei-staging-logs \
              --log-opt awslogs-create-group=true \
              --name lacrei-container \
              ghcr.io/matheuzlima/desafio-lacrei-app:latest
              
      - name: Validar Deploy de Staging (Smoke Test)
        run: |
          sleep 40
          curl -f https://desafio-lacrei.sparkflux.com.br/status
