name: Deploy em Staging

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ghcr.io/matheuzlima/desafio-lacrei-app:latest

      - name: Deploy no Servidor EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # 1. Login no Registry (necessário para baixar imagem privada)
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 2. Baixar a nova versão
            docker pull ghcr.io/matheuzlima/desafio-lacrei-app:latest
            
            # 3. Parar e remover o antigo (silencia erros se não existir com || true)
            docker stop lacrei-container || true
            docker rm lacrei-container || true
            
            # 4. Subir o novo container
            docker run -d \
              -p 3000:3000 \
              --restart unless-stopped \
              --log-driver=awslogs \
              --log-opt awslogs-region=us-east-1 \
              --log-opt awslogs-group=lacrei-staging-logs \
              --log-opt awslogs-create-group=true \
              --name lacrei-container \
              ghcr.io/matheuzlima/desafio-lacrei-app:latest
              
      - name: Validar Deploy de Staging (Smoke Test)
        run: |
          sleep 20 #tempo para testar o link
          curl -f --retry 5 --retry-delay 5 https://desafio-lacrei.sparkflux.com.br/status